version: "3.1"

networks:
  net1:

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: hw_asyncio
    ports:
      - "5431:5432"
    networks:
      net1:
        aliases:
          - database